version: "3.9"

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    networks:
      - appnet

  frontend:
    build: ./frontend
    networks:
      - appnet

  backend:
    build: ./backend
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - REDIS_HOST=redis
    networks:
      - appnet

  mongo:
    image: mongo:7
    networks:
      - appnet

  redis:
    image: redis:7
    networks:
      - appnet

networks:
  appnet:
